In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [10]:
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    # 'I am learning Natural Language Processing',
]

In [11]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words']

In [12]:
voc_size=10000  # vocabulary size of dict.

In [13]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[4728, 6665, 9517, 6638], [4728, 6665, 9517, 7565], [4728, 5255, 9517, 4167], [2143, 2702, 6198, 9864, 6955], [2143, 2702, 6198, 9864, 5502], [4688, 4728, 2176, 9517, 9427]]


word embedding representation

In [15]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

In [16]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4728 6665 9517 6638]
 [   0    0    0    0 4728 6665 9517 7565]
 [   0    0    0    0 4728 5255 9517 4167]
 [   0    0    0 2143 2702 6198 9864 6955]
 [   0    0    0 2143 2702 6198 9864 5502]
 [   0    0    0 4688 4728 2176 9517 9427]]


In [17]:
dim=10

In [21]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')
model.build(input_shape=(None, sent_length))  # Manually build the model

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [22]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [20]:
# import tensorflow as tf
# import keras

# print("TensorFlow version:", tf.__version__)
# print("Keras version:", keras.__version__)


TensorFlow version: 2.18.0
Keras version: 3.8.0


In [23]:
# embedding metrics
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 190ms/step
[[[-0.02861402 -0.00801746  0.02508285  0.01921168  0.00585241
   -0.03293339  0.04699287  0.00426524  0.04184842  0.027659  ]
  [-0.02861402 -0.00801746  0.02508285  0.01921168  0.00585241
   -0.03293339  0.04699287  0.00426524  0.04184842  0.027659  ]
  [-0.02861402 -0.00801746  0.02508285  0.01921168  0.00585241
   -0.03293339  0.04699287  0.00426524  0.04184842  0.027659  ]
  [-0.02861402 -0.00801746  0.02508285  0.01921168  0.00585241
   -0.03293339  0.04699287  0.00426524  0.04184842  0.027659  ]
  [-0.00725215  0.04492041 -0.04201666  0.04836244  0.03995805
    0.01788309  0.01971411 -0.0279008  -0.04870141  0.03695634]
  [-0.04503212  0.03488007 -0.00226544 -0.01599995 -0.01078857
    0.03542403  0.04742033 -0.02716954 -0.00567884 -0.01472545]
  [-0.02815784 -0.04696805  0.02280969 -0.03777945 -0.04680315
   -0.02779028 -0.04186152  0.03653376 -0.04971529 -0.02436336]
  [ 0.00137187 -0.03738803  0.04736004 -0.00612498  0.04977309
   -0.025

In [24]:
embedded_docs[0]

array([   0,    0,    0,    0, 4728, 6665, 9517, 6638], dtype=int32)